MRTPlus/Models/Portfolio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using MRTPlus.Models;

namespace MRTPlus.Models
{
    public class Portfolio
    {
        
        public int PortfolioID { get; set; }

        [Display(Name = "Portfolio Title")]
        public string Title { get; set; }
        public string FY { get; set; }
        public int PortfolioTypeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }

        [Display(Name = "Project Type")]
        public virtual PortfolioType PortfolioType { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        //public virtual ICollection<File> Files { get; set; }
        //public virtual ICollection<Project> Projects { get; set; }
    }
}

MRTPlus/Models/PortfolioType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using MRTPlus.Models;



namespace MRTPlus.Models
{
    public class PortfolioType
    {
        [Display(Name = "Portfolio Title")]
        public int PortfolioTypeID { get; set; }
        public string Title { get; set; }
        
    }
}

MRTPlus/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MRTPlus.Models;
using MRTPlus.DAL;

namespace MRTPlus.Controllers
{
    public class PortfolioController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Portfolio/
        public ActionResult Index()
        {
            var portfolios = db.Portfolios.Include(p => p.PortfolioType);
            return View(portfolios.ToList());
        }

        // GET: /Portfolio/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Portfolio portfolio = db.Portfolios.Find(id);
            if (portfolio == null)
            {
                return HttpNotFound();
            }
            return View(portfolio);
        }

        // GET: /Portfolio/Create
        public ActionResult Create()
        {
            ViewBag.PortfolioTypeID = new SelectList(db.PortfolioTypes, "PortfolioTypeID", "Title");
            return View();
        }

        // POST: /Portfolio/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="PortfolioID,Title,FY,PortfolioTypeID,Date")] Portfolio portfolio)
        {
            if (ModelState.IsValid)
            {
                db.Portfolios.Add(portfolio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PortfolioTypeID = new SelectList(db.PortfolioTypes, "PortfolioTypeID", "Title", portfolio.PortfolioTypeID);
            return View(portfolio);
        }

        // GET: /Portfolio/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Portfolio portfolio = db.Portfolios.Find(id);
            if (portfolio == null)
            {
                return HttpNotFound();
            }
            ViewBag.PortfolioTypeID = new SelectList(db.PortfolioTypes, "PortfolioTypeID", "Title", portfolio.PortfolioTypeID);
            return View(portfolio);
        }

        // POST: /Portfolio/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="PortfolioID,Title,FY,PortfolioTypeID,Date")] Portfolio portfolio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(portfolio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PortfolioTypeID = new SelectList(db.PortfolioTypes, "PortfolioTypeID", "Title", portfolio.PortfolioTypeID);
            return View(portfolio);
        }

        // GET: /Portfolio/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Portfolio portfolio = db.Portfolios.Find(id);
            if (portfolio == null)
            {
                return HttpNotFound();
            }
            return View(portfolio);
        }

        // POST: /Portfolio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Portfolio portfolio = db.Portfolios.Find(id);
            db.Portfolios.Remove(portfolio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MRTPlus/Views/Portfolio/Create.cshtml
@model MRTPlus.Models.Portfolio

@{
    ViewBag.Title = "Create";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Create</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Create</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>



<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Create Portfolio</h5>
                </div>
                <div class="ibox-content">

				@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FY, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FY)
                @Html.ValidationMessageFor(model => model.FY)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PortfolioTypeID, "PortfolioTypeID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.DropDownList("PortfolioTypeID", null, string.Empty, new { @class = "form-control" , style = "width: 250px;" })
               
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date)
                @Html.ValidationMessageFor(model => model.Date)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
				@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-white"})
            </div>
        </div>
    </div>
}

                </div>
            </div>
        </div>
    </div>
 </div>

 

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MRTPlus/Views/Portfolio/Delete.cshtml
@model MRTPlus.Models.Portfolio

@{
    ViewBag.Title = "Delete";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Delete</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Delete</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Portfolio</h5>
                </div>
                <div class="ibox-content">
				<h4 class="text-danger">Are you sure you want to delete this?</h4>
				 <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PortfolioType.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PortfolioType.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-white"})
        </div>
    }



                </div>
            </div>
        </div>
    </div>
 </div>



MRTPlus/Views/Portfolio/Details.cshtml
@model MRTPlus.Models.Portfolio

@{
    ViewBag.Title = "Details";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Details</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Details</strong>
            </li>
        </ol>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Details Portfolio</h5>
                </div>
                <div class="ibox-content">


				    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PortfolioType.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PortfolioType.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>


	    @Html.ActionLink("Edit", "Edit", new { id = Model.PortfolioID }, new { @class = "btn btn-primary"})
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-white"})

                </div>
            </div>
        </div>
    </div>
 </div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Associated Projects</h5>
                </div>
                <div class="ibox-content">
                    <table class="table table-hover">
                        <tr>
                            <th>Project Title</th>
                            <th>TEC</th>
                            <th>Description</th>
                            <th>Date</th>
                        </tr>
                        @foreach (var item in Model.Enrollments)
                        {
                            <tr>
                                <td>
                                    @Html.ActionLink(item.Project.Title, "Details", "Project", new { id = item.ProjectID }, null)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Project.TEC)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Project.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Project.EnrollmentDate)
                                </td>
                            </tr>
                        }
                    </table>


                    
                </div>
            </div>
        </div>
    </div>
</div>




















MRTPlus/Views/Portfolio/Edit.cshtml
@model MRTPlus.Models.Portfolio

@{
    ViewBag.Title = "Edit";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Edit</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Edit</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>




<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Edit Portfolio</h5>
                </div>
                <div class="ibox-content">

				@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.PortfolioID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FY, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FY)
                @Html.ValidationMessageFor(model => model.FY)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PortfolioTypeID, "PortfolioTypeID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PortfolioTypeID", String.Empty)
                @Html.ValidationMessageFor(model => model.PortfolioTypeID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date)
                @Html.ValidationMessageFor(model => model.Date)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
				@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-white"})
            </div>
        </div>
    </div>
}


                </div>
            </div>
        </div>
    </div>
 </div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MRTPlus/Views/Portfolio/Index.cshtml
@model IEnumerable<MRTPlus.Models.Portfolio>

@{
    ViewBag.Title = "Index";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Index</h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong>Portfolio</strong>
            </li>
        </ol>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List of Portfolio</h5>
					<div class="ibox-tools">
						@Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-xs"})
					</div>
                </div>
                <div class="ibox-content">

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PortfolioType.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FY)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <h4>@Html.ActionLink(item.Title, "Details", "Portfolio", new { id = item.PortfolioID }, null)</h4>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PortfolioType.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FY)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        
        <td>
			@Html.ActionLink("Details", "Details", new { id=item.PortfolioID }, new { @class = "btn btn-primary btn-sm"})
            @Html.ActionLink("Edit", "Edit", new { id=item.PortfolioID }, new { @class = "btn btn-white btn-sm"})
            @Html.ActionLink("Delete", "Delete", new { id=item.PortfolioID }, new { @class = "btn btn-white btn-sm"})
        </td>
    </tr>
}

</table>

                </div>
            </div>
        </div>
    </div>
 </div>


MRTPlus/Views/Portfolio/_PieChartView.cshtml

<div id="piechart" style="width: 200px; height: 100px;"></div>